global using COURSE_ASH.Globals;
global using COURSE_ASH.Model;
global using COURSE_ASH.View;
global using COURSE_ASH.ViewModel;
global using COURSE_ASH.Services;
global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Input;
global using System.ComponentModel;
global using System.Collections.ObjectModel;
